version: '2'
services:

  web:
    build:
      context: ./www
      dockerfile: Dockerfile-www
    ports:
      - "3000:3000"
    command: npm start
    working_dir: /opt/www
    environment:
      NODE_PATH: /opt/node
    volumes:
      - ./www:/opt/www

  api:
    build:
      context: ./api
      dockerfile: Dockerfile-nodejs
    ports:
      - "5000:5000"
    command: npm start
    working_dir: /opt/app
    environment:
      NODE_PATH: /opt/node
    volumes:
      - ./api:/opt/app
    links:
      - mongo

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    links:
      - api
      - web
    ports:
        - "80:80"

  mongo:
    image: mongo:3.0.4
    hostname: mongo
    volumes:
      - /data/db
    ports:
      - "27017:27017"
    command: --smallfiles --rest
